#############################################################################
# Makefile for building: Hierarchy
# Generated by qmake (3.0) (Qt 5.3.1)
# Project:  Hierarchy.pro
# Template: app
# Command: /home/csunix/linux/apps/install/qt/5.3.1/5.3/gcc_64/bin/qmake -o Makefile Hierarchy.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/linux-g++ -I. -I. -I/opt/local/include -I/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include -I/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtOpenGL -I/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets -I/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui -I/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/cserv1_a/apps/install/qt/5.3.1/5.3/gcc_64 -Wl,-rpath,/home/cserv1_a/apps/install/qt/5.3.1/5.3/gcc_64/lib
LIBS          = $(SUBLIBS) -lglut -lGLU -L/home/csunix/linux/apps/install/qt/5.3.1/5.3/gcc_64/lib -lQt5OpenGL -L/home/cserv1_a/apps/install/qt/5.3.1/5.3/gcc_64/lib -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/csunix/linux/apps/install/qt/5.3.1/5.3/gcc_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Main.cpp \
		HierarchyWidget.cpp \
		SolidCubeWindow.cpp moc_HierarchyWidget.cpp
OBJECTS       = Main.o \
		HierarchyWidget.o \
		SolidCubeWindow.o \
		moc_HierarchyWidget.o
DIST          = /home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/spec_pre.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/common/shell-unix.conf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/common/unix.conf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/common/linux.conf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/common/gcc-base.conf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/common/g++-base.conf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/common/g++-unix.conf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/qconfig.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/qt_functions.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/qt_config.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/linux-g++/qmake.conf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/spec_post.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/exclusive_builds.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/default_pre.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/resolve_config.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/default_post.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/warn_on.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/qt.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/resources.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/moc.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/unix/opengl.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/uic.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/unix/thread.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/testcase_targets.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/exceptions.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/yacc.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/lex.prf \
		Hierarchy.pro Main.cpp \
		HierarchyWidget.cpp \
		SolidCubeWindow.cpp
QMAKE_TARGET  = Hierarchy
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = Hierarchy


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Hierarchy.pro /home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/linux-g++/qmake.conf /home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/spec_pre.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/common/shell-unix.conf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/common/unix.conf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/common/linux.conf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/common/gcc-base.conf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/common/g++-base.conf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/common/g++-unix.conf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/qconfig.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/qt_functions.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/qt_config.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/linux-g++/qmake.conf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/spec_post.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/exclusive_builds.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/default_pre.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/resolve_config.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/default_post.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/warn_on.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/qt.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/resources.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/moc.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/unix/opengl.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/uic.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/unix/thread.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/testcase_targets.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/exceptions.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/yacc.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/lex.prf \
		Hierarchy.pro \
		/home/csunix/linux/apps/install/qt/5.3.1/5.3/gcc_64/lib/libQt5OpenGL.prl \
		/home/csunix/linux/apps/install/qt/5.3.1/5.3/gcc_64/lib/libQt5Widgets.prl \
		/home/csunix/linux/apps/install/qt/5.3.1/5.3/gcc_64/lib/libQt5Gui.prl \
		/home/csunix/linux/apps/install/qt/5.3.1/5.3/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -o Makefile Hierarchy.pro
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/spec_pre.prf:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/common/shell-unix.conf:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/common/unix.conf:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/common/linux.conf:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/common/gcc-base.conf:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/common/g++-base.conf:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/common/g++-unix.conf:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/qconfig.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/qt_functions.prf:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/qt_config.prf:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/linux-g++/qmake.conf:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/spec_post.prf:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/exclusive_builds.prf:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/default_pre.prf:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/resolve_config.prf:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/default_post.prf:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/warn_on.prf:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/qt.prf:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/resources.prf:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/moc.prf:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/unix/opengl.prf:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/uic.prf:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/unix/thread.prf:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/testcase_targets.prf:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/exceptions.prf:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/yacc.prf:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/lex.prf:
Hierarchy.pro:
/home/csunix/linux/apps/install/qt/5.3.1/5.3/gcc_64/lib/libQt5OpenGL.prl:
/home/csunix/linux/apps/install/qt/5.3.1/5.3/gcc_64/lib/libQt5Widgets.prl:
/home/csunix/linux/apps/install/qt/5.3.1/5.3/gcc_64/lib/libQt5Gui.prl:
/home/csunix/linux/apps/install/qt/5.3.1/5.3/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Hierarchy.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/Hierarchy1.0.0 || mkdir -p .tmp/Hierarchy1.0.0
	$(COPY_FILE) --parents $(DIST) .tmp/Hierarchy1.0.0/ && $(COPY_FILE) --parents HierarchyWidget.h SolidCubeWindow.h .tmp/Hierarchy1.0.0/ && $(COPY_FILE) --parents Main.cpp HierarchyWidget.cpp SolidCubeWindow.cpp .tmp/Hierarchy1.0.0/ && (cd `dirname .tmp/Hierarchy1.0.0` && $(TAR) Hierarchy1.0.0.tar Hierarchy1.0.0 && $(COMPRESS) Hierarchy1.0.0.tar) && $(MOVE) `dirname .tmp/Hierarchy1.0.0`/Hierarchy1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Hierarchy1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_HierarchyWidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_HierarchyWidget.cpp
moc_HierarchyWidget.cpp: /home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtOpenGL/QGLWidget \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtOpenGL/qgl.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qopengl.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qglobal.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qconfig.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qfeatures.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qtypetraits.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qsysinfo.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qlogging.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qflags.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qmutex.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qnumeric.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qt_windows.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qopengles2ext.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qopenglext.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qwidget.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qwindowdefs.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qobjectdefs.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qnamespace.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qobject.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qstring.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qchar.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qbytearray.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qrefcount.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qarraydata.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qstringbuilder.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qlist.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qalgorithms.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qiterator.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qcoreevent.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qscopedpointer.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qmetatype.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qisenum.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qobject_impl.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qmargins.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qpaintdevice.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qrect.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qsize.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qpoint.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qpalette.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qcolor.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qrgb.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qstringlist.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qdatastream.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qiodevice.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qpair.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qregexp.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qstringmatcher.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qbrush.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qvector.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qmatrix.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qpolygon.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qregion.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qline.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qtransform.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qpainterpath.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qimage.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qpixmap.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qsharedpointer.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qshareddata.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qhash.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qfont.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qfontmetrics.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qfontinfo.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qcursor.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qkeysequence.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qevent.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qvariant.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qmap.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qdebug.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qtextstream.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qlocale.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qset.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qurl.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qurlquery.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qfile.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qfiledevice.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qvector2d.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qtouchdevice.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qpaintengine.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qpainter.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qtextoption.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qpen.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtOpenGL/qglcolormap.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtOpenGL/qtopenglglobal.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/QSurfaceFormat \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qsurfaceformat.h \
		HierarchyWidget.h
	/home/csunix/linux/apps/install/qt/5.3.1/5.3/gcc_64/bin/moc $(DEFINES) -I/home/csunix/linux/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/linux-g++ -I/home/cserv1_a/soc_staff/scsmdk/graphics/hierarchy/hierarchy -I/home/cserv1_a/soc_staff/scsmdk/graphics/hierarchy/hierarchy -I/opt/local/include -I/home/csunix/linux/apps/install/qt/5.3.1/5.3/gcc_64/include -I/home/csunix/linux/apps/install/qt/5.3.1/5.3/gcc_64/include/QtOpenGL -I/home/csunix/linux/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets -I/home/csunix/linux/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui -I/home/csunix/linux/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore HierarchyWidget.h -o moc_HierarchyWidget.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

Main.o: Main.cpp /home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/QApplication \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qapplication.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qcoreapplication.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qglobal.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qconfig.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qfeatures.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qtypetraits.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qsysinfo.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qlogging.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qflags.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qmutex.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qnumeric.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qstring.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qchar.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qbytearray.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qrefcount.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qnamespace.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qarraydata.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qstringbuilder.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qobject.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qobjectdefs.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qlist.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qalgorithms.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qiterator.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qcoreevent.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qscopedpointer.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qmetatype.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qisenum.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qobject_impl.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qeventloop.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qwindowdefs.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qpoint.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qsize.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qcursor.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qdesktopwidget.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qwidget.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qmargins.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qpaintdevice.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qrect.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qpalette.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qcolor.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qrgb.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qstringlist.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qdatastream.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qiodevice.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qpair.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qregexp.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qstringmatcher.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qbrush.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qvector.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qmatrix.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qpolygon.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qregion.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qline.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qtransform.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qpainterpath.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qimage.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qpixmap.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qsharedpointer.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qshareddata.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qhash.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qfont.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qfontmetrics.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qfontinfo.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qkeysequence.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qevent.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qvariant.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qmap.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qdebug.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qtextstream.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qlocale.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qset.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qurl.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qurlquery.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qfile.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qfiledevice.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qvector2d.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qtouchdevice.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qguiapplication.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qinputmethod.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/QVBoxLayout \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qboxlayout.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qlayout.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qlayoutitem.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qgridlayout.h \
		SolidCubeWindow.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtOpenGL/QGLWidget \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtOpenGL/qgl.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qopengl.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qt_windows.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qopengles2ext.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qopenglext.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qpaintengine.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qpainter.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qtextoption.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qpen.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtOpenGL/qglcolormap.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtOpenGL/qtopenglglobal.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/QSurfaceFormat \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qsurfaceformat.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/QMenuBar \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qmenubar.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qmenu.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qicon.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qaction.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qactiongroup.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/QSlider \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qslider.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qabstractslider.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/QBoxLayout \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/QTimer \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qtimer.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qbasictimer.h \
		HierarchyWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Main.o Main.cpp

HierarchyWidget.o: HierarchyWidget.cpp /home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtOpenGL/QGLWidget \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtOpenGL/qgl.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qopengl.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qglobal.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qconfig.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qfeatures.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qtypetraits.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qsysinfo.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qlogging.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qflags.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qmutex.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qnumeric.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qt_windows.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qopengles2ext.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qopenglext.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qwidget.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qwindowdefs.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qobjectdefs.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qnamespace.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qobject.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qstring.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qchar.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qbytearray.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qrefcount.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qarraydata.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qstringbuilder.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qlist.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qalgorithms.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qiterator.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qcoreevent.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qscopedpointer.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qmetatype.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qisenum.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qobject_impl.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qmargins.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qpaintdevice.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qrect.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qsize.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qpoint.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qpalette.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qcolor.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qrgb.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qstringlist.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qdatastream.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qiodevice.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qpair.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qregexp.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qstringmatcher.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qbrush.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qvector.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qmatrix.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qpolygon.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qregion.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qline.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qtransform.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qpainterpath.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qimage.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qpixmap.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qsharedpointer.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qshareddata.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qhash.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qfont.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qfontmetrics.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qfontinfo.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qcursor.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qkeysequence.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qevent.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qvariant.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qmap.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qdebug.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qtextstream.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qlocale.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qset.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qurl.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qurlquery.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qfile.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qfiledevice.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qvector2d.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qtouchdevice.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qpaintengine.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qpainter.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qtextoption.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qpen.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtOpenGL/qglcolormap.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtOpenGL/qtopenglglobal.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/QSurfaceFormat \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qsurfaceformat.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/QSlider \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qslider.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qabstractslider.h \
		HierarchyWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o HierarchyWidget.o HierarchyWidget.cpp

SolidCubeWindow.o: SolidCubeWindow.cpp SolidCubeWindow.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtOpenGL/QGLWidget \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtOpenGL/qgl.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qopengl.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qglobal.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qconfig.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qfeatures.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qtypetraits.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qsysinfo.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qlogging.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qflags.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qmutex.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qnumeric.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qt_windows.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qopengles2ext.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qopenglext.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qwidget.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qwindowdefs.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qobjectdefs.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qnamespace.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qobject.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qstring.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qchar.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qbytearray.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qrefcount.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qarraydata.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qstringbuilder.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qlist.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qalgorithms.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qiterator.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qcoreevent.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qscopedpointer.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qmetatype.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qisenum.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qobject_impl.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qmargins.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qpaintdevice.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qrect.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qsize.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qpoint.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qpalette.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qcolor.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qrgb.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qstringlist.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qdatastream.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qiodevice.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qpair.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qregexp.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qstringmatcher.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qbrush.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qvector.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qmatrix.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qpolygon.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qregion.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qline.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qtransform.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qpainterpath.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qimage.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qpixmap.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qsharedpointer.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qshareddata.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qhash.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qfont.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qfontmetrics.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qfontinfo.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qcursor.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qkeysequence.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qevent.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qvariant.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qmap.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qdebug.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qtextstream.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qlocale.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qset.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qurl.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qurlquery.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qfile.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qfiledevice.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qvector2d.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qtouchdevice.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qpaintengine.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qpainter.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qtextoption.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qpen.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtOpenGL/qglcolormap.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtOpenGL/qtopenglglobal.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/QSurfaceFormat \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qsurfaceformat.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/QMenuBar \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qmenubar.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qmenu.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qicon.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qaction.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qactiongroup.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/QSlider \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qslider.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qabstractslider.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/QBoxLayout \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qboxlayout.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qlayout.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qlayoutitem.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qgridlayout.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/QTimer \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qtimer.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qbasictimer.h \
		HierarchyWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SolidCubeWindow.o SolidCubeWindow.cpp

moc_HierarchyWidget.o: moc_HierarchyWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_HierarchyWidget.o moc_HierarchyWidget.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

